#!/usr/bin/env bash

function detect_php() {
    if [[ ${PHP?"Need to set PHP version"} ]]; then
        export PHPFPM_BIN="/opt/php/$PHP/sbin/php-fpm"
        export PHP_BIN="/opt/php/$PHP/bin/php"
        export PHP_DIR="/opt/php/$PHP/bin/"
        export PHPFPM_DIR="/opt/php/$PHP/sbin/"
        export PATH=$PATH:$PHPFPM_DIR:$PHP_DIR
        export MYSQL_SERVER="$(env | egrep '*_MYSQL_1_PORT' | awk -F'=' '{print $2}')"
        export MYSQL_SERVER_HOST="$(echo $MYSQL_SERVER | awk -F':' '{print $2}' | awk -F'//' '{print $2}')"
        echo "env[MYSQL_SERVER_HOST] = $MYSQL_SERVER_HOST" > /opt/php/$PHP/etc/env.conf
        echo "php_admin_value[date.timezone] = $TIMEZONE" >> /opt/php/$PHP/etc/env.conf
        echo "php_admin_value[post_max_size] = 2000M" >> /opt/php/$PHP/etc/env.conf
        echo "php_admin_value[max_execution_time] = 3000" >> /opt/php/$PHP/etc/env.conf
        echo "php_admin_value[max_input_time] = 3000" >> /opt/php/$PHP/etc/env.conf
        echo "php_admin_value[upload_max_filesize] = 2000M" >> /opt/php/$PHP/etc/env.conf
        echo "php_admin_value[upload_max_filesize] = 2000M" >> /opt/php/$PHP/etc/env.conf
        if [[ $XDEBUG ]]; then
            echo "Xdebug host is: $XDEBUG"
            if [[ ${XDEBUG_PORT?"Need to set XDEBUG_PORT"} ]]; then
                echo "Xdebug port is: $XDEBUG_PORT"
                echo "xdebug.remote_host = $XDEBUG" >> /opt/php/$PHP/etc/conf.d/xdebug.ini
                echo "xdebug.idekey = $XDEBUG_IDEKEY" >> /opt/php/$PHP/etc/conf.d/xdebug.ini
                echo "xdebug.remote_port = $XDEBUG_PORT" >> /opt/php/$PHP/etc/conf.d/xdebug.ini
                echo "xdebug.remote_enable = 1" >> /opt/php/$PHP/etc/conf.d/xdebug.ini
                echo "xdebug.remote_mode = req" >> /opt/php/$PHP/etc/conf.d/xdebug.ini
            fi
        fi

        env&&
        $PHPFPM_BIN -v&&
        $PHPFPM_BIN -m
    fi
}

function start_php() {
    logger info "Starting PHP $PHP"
    exec $PHPFPM_BIN -R
}

{  # try
    detect_php &&
    start_php
} || {  # catch
    echo "-----> Failed detecting PHP"
    exit 1
}